/*
 * @lc app=leetcode id=389 lang=cpp
 *
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (53.68%)
 * Likes:    573
 * Dislikes: 247
 * Total Accepted:    163K
 * Total Submissions: 302.6K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 * 
 */

// @lc code=start
class Solution {
public:
    char findTheDifference(string s, string t) {
        std::sort(s.begin(), s.end());
        std::sort(t.begin(), t.end());
        char ret = ' ';
        bool isFind = false;
        for(size_t i = 0; i< s.size(); ++i){
            if(s[i]!=t[i]) {
                ret = t[i];
                isFind = true;
                break;
            }
        }
        if(!isFind) ret = t[t.size()-1];

        return ret;
    }
    // Accepted
    // 54/54 cases passed (8 ms)
    // Your runtime beats 27.6 % of cpp submissions
    // Your memory usage beats 77.78 % of cpp submissions (9 MB)
};
// @lc code=end

